development: &default
  secret_token: ENV['secret_token']
  authorization_header: 'X-Pender-Token'
  timeout: 25
  public_url: 'http://localhost:3200'
  redis_host: ENV['redis_host']
  redis_port: ENV['redis_port']
  redis_database: 1

  # File storage on S3 or API equivalent
  #
  # REQUIRED
  # Use values below for local development
  #
  storage:
    # endpoint: ENV['endpoint']
    access_key: ENV['access_key']
    secret_key: ENV['secret_key']
    bucket: ENV['bucket']
    bucket_region: ENV['bucket_region']
    video_bucket: ENV['video_bucket']
    video_asset_path: 'https://pender-api.herokuapp.com/video'
    
  # Exception reporting using Airbrake or API equivalent https://airbrake.io/
  #
  # OPTIONAL
  #
  airbrake:
    host: # '<AIRBRAKE HOST>'
    port: # '<AIRBRAKE PORT>'
    project_key: # '<AIRBRAKE PROJECT KEY>'
    environment: # '<AIRBRAKE ENVIRONMENT>'

  # Google API
  #
  # REQUIRED for YouTube links
  # OPTIONAL for Safe Browsing Lookup API https://developers.google.com/safe-browsing/v4/lookup-api
  # To get a key, follow these instructions https://developers.google.com/safe-browsing/v4/get-started
  #
  google_api_key: ENV['google_api_key']

  # Twitter API
  #
  # REQUIRED for Twitter posts
  #
  twitter_consumer_key: ENV['twitter_consumer_key']
  twitter_consumer_secret: ENV['twitter_consumer_secret']
  twitter_access_token: ENV['twitter_access_token']
  twitter_access_token_secret: ENV['twitter_access_token_secret']

  # Facebook API
  #
  # REQUIRED for Facebook social metrics
  #
  facebook_app_id: ENV['facebook_app_id']
  facebook_app_secret: ENV['facebook_app_secret']

  # Luminati proxy service https://luminati.io/
  #
  # OPTIONAL
  #
  proxy_host: # '<LUMINATI HOST>'
  proxy_port: # '<LUMINATI PORT>'
  proxy_user_prefix: # '<LUMINATI ACCOUNT PREFIX>'
  proxy_pass: # '<LUMINATI ACCOUNT PASSWORD>'

  # Special instructions to access specific domains
  #
  # OPTIONAL
  #
  hosts:
    <HOST DOMAIN>:
      country: '<COUNTRY CODE FOR PROXY SETTING>'
      cf_credentials: '<CLOUDFLARE CREDENTIALS>'

  # CloudFlare caching https://support.cloudflare.com/hc/en-us/categories/200275248-Caching
  #
  # OPTIONAL
  #
  cloudflare_auth_email: # '<CLOUDFLARE AUTH EMAIL>'
  cloudflare_auth_key: # '<CLOUDFLARE AUTH KEY>'
  cloudflare_zone: # '<CLOUDFLARE ZONE>'

test:
  <<: *default
  chrome_debug_port: 9444

production:
  <<: *default
  public_url: 'https://pender-api.herokuapp.com'
